# Generated by Django 4.2.7 on 2024-08-15 22:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('empresa', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vaga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('funcao', models.CharField(max_length=100)),
                ('requisitos', models.CharField(max_length=200)),
                ('descricao', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('disponivel', 'Disponível'), ('preenchida', 'Preenchida')], default='disponivel', max_length=20)),
                ('valorSalarial', models.CharField(max_length=20)),
                ('cargaHoraria', models.CharField(max_length=100)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empresa.empresa')),
            ],
        ),
    ]
